### ISSUE TITLE
New paper

### ISSUE THREAD

**Issue by J4Q8** [chrisliu298/awesome-llm-unlearning#3]
Hi! 

Thanks for creating the repository. It was really useful for literature review!

I believe that our paper: https://arxiv.org/abs/2409.18025 fits the topic of your repository. Could you add it?

Best,
Jakub

**Comment by chrisliu298** [comment]
Hi!

Thanks for mentioning it. I have included your paper in the latest commit. Great work, by the way!

Closing this issue now.
